export const weatherCodeMap: Record<number, string> = {
    0: 'Clear',
    1: 'Partly Cloudy',
    2: 'Partly Cloudy',
    3: 'Cloudy',
    45: 'Fog',
    48: 'Fog',
    51: 'Light Rain',
    53: 'Light Rain',
    55: 'Light Rain',
    56: 'Light Rain',
    57: 'Light Rain',
    61: 'Light Rain',
    63: 'Moderate Rain',
    65: 'Heavy Rain',
    66: 'Light Rain',
    67: 'Heavy Rain',
    71: 'Light Snow',
    73: 'Moderate Snow',
    75: 'Heavy Snow',
    77: 'Snow Grains',
    80: 'Light Rain',
    81: 'Moderate Rain',
    82: 'Rain',
    85: 'Light Snow',
    86: 'Heavy Snow',
    95: 'Thunderstorm',
    96: 'Thunderstorm',
    99: 'Thunderstorm',
};

export const WEATHER_ICON_MAP: Record<number, string> = {
    0: 'clear',
    1: 'partly-cloudy',
    2: 'partly-cloudy',
    3: 'cloudy',
    45: 'fog',
    48: 'fog',
    51: 'light-rain',
    53: 'light-rain',
    55: 'light-rain',
    56: 'light-rain',
    57: 'light-rain',
    61: 'light-rain',
    63: 'light-rain',
    65: 'rain',
    66: 'rain',
    67: 'rain',
    71: 'snow',
    73: 'snow',
    75: 'snow',
    77: 'snow',
    80: 'light-rain',
    81: 'rain',
    82: 'rain',
    85: 'snow',
    86: 'snow',
    95: 'thunderstorm',
    96: 'thunderstorm',
    99: 'thunderstorm',
}
